파이토치는 실행할때마다 텐서플로와 다르게 컴파일 하지 않아도 된다

텐서 = n차원 스칼라 배열

## 텐서 만들기

In [22]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print('값: {}'.format(x))

In [23]:
import torch

In [24]:
describe(torch.Tensor(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 0.0000e+00, -1.5846e+29,  0.0000e+00],
        [-1.5846e+29,  8.4078e-45,  0.0000e+00]])


In [25]:
describe(torch.rand(2,3)) #균등 분포
describe(torch.randn(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[0.1816, 0.8665, 0.8586],
        [0.9194, 0.0136, 0.3890]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[ 0.0521, -1.4825,  0.4356],
        [ 0.7226, -0.7588,  0.6776]])


In [26]:
describe(torch.zeros(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
x = torch.ones(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x.fill_(5)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [29]:
#파이썬 리스트로 텐서 만들기
x = torch.Tensor([[1,2,3],
                 [4,5,6]])

In [30]:
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [31]:
#넘파이 배열을 사용하면 텐서 타입이 FloatTensor가 아닌 DoubleTensor로 된다
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: tensor([[0.7870, 0.9777, 0.1840],
        [0.2515, 0.5271, 0.6638]], dtype=torch.float64)


## 텐서 타입과 크기

기본 텐서 타입: torch.FloatTensor

In [32]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[1, 2, 3],
        [4, 5, 6]])


In [34]:
x = torch.tensor([[1,2,3],
                 [4,5,6]],dtype = torch.int64)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
x = x.float()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 텐서 연산

In [37]:
x = torch.randn(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[-0.5861, -0.7227, -2.0223],
        [-0.1183,  1.1687, -0.6563]])


In [38]:
describe(torch.add(x,x))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[-1.1723, -1.4454, -4.0446],
        [-0.2365,  2.3375, -1.3126]])


In [39]:
describe(x+x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: tensor([[-1.1723, -1.4454, -4.0446],
        [-0.2365,  2.3375, -1.3126]])


텐서별 차원 연산: 2D 텐서는 행을 차원0, 열을 차원1로 표시

In [41]:
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: tensor([0, 1, 2, 3, 4, 5])


In [42]:
x = x.view(2,3) #reshape와 같음. ㅇ동일한 데이터 공유하는 새로운 텐서
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])


In [44]:
describe(torch.sum(x,dim=0))

타입: torch.LongTensor
크기: torch.Size([3])
값: tensor([3, 5, 7])


In [45]:
describe(torch.sum(x,dim=1))

타입: torch.LongTensor
크기: torch.Size([2])
값: tensor([ 3, 12])


In [46]:
describe(torch.transpose(x,0,1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: tensor([[0, 3],
        [1, 4],
        [2, 5]])


## 인덱싱, 슬라이싱, 연결

In [48]:
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
describe(x[:1,:2])

타입: torch.LongTensor
크기: torch.Size([1, 2])
값: tensor([[0, 1]])


In [50]:
#복잡한 인덱싱, 연속적이지 않은 텐서 인덱스 참조하기
indices = torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: tensor([[0, 2],
        [3, 5]])


In [51]:
describe(indices)

타입: torch.LongTensor
크기: torch.Size([2])
값: tensor([0, 2])


In [52]:
#인덱스가 LongTensor라는 사실이 파이토치함수 사용 시 필수조건

In [53]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [55]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x,dim=0,index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [0, 1, 2]])


In [56]:
#텐서 연결 내장함수로도 가능
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])


In [58]:
describe(torch.cat([x,x],dim=0)) #torch.cat(): tensor 합치기

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [59]:
describe(torch.stack([x,x]))

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [60]:
x1 = torch.arange(6).view(2,3)
describe(x1)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: tensor([[0, 1, 2],
        [3, 4, 5]])


In [65]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

#torch.mm(): 행렬곱

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


## 텐서와 계산 그래프

##### requires_grad = True: 그래디언트 기반 학습에 필요한 손실 함수와 텐서의 그레디언트 기록하는 부가 연산 활성화

In [68]:
x = torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [69]:
y = (x+2) * (x+5) +3
describe(y)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


In [70]:
z = y.mean()
describe(z)
z.backward() #역방향 계산
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 21.0
False


일반적으로 그래디언트: 함수 입력에 대한 함수 출력의 기울기
    
    - 계산 그래프에서 그래디언트는 파라미터마다 존재
    - .grad: 노드에 대한 그래디언트
    - 옵티마이저는 .grad를 바탕으로 파라미터값 업데이트

## CUDA 텐서

지금까지는 텐서를 CPU에 할당했지만 GPU 메모리 할당하는 방법?

In [74]:
print(torch.cuda.is_available()) #여기서는 쿠다 못쓰네

False


## 문제 풀어보기

In [78]:
#1
a = torch.rand(3,3)
a.unsqueeze(0)

#squeeze(): size가 1인차원 없애줌

tensor([[[0.3156, 0.9886, 0.6581],
         [0.4306, 0.6468, 0.3770],
         [0.3353, 0.7610, 0.5202]]])

In [79]:
#2
a.squeeze(0)

tensor([[0.3156, 0.9886, 0.6581],
        [0.4306, 0.6468, 0.3770],
        [0.3353, 0.7610, 0.5202]])

In [80]:
#3
3 + torch.rand(5,3) *4

tensor([[3.1414, 3.8007, 6.2886],
        [3.8901, 4.3766, 6.0061],
        [3.6472, 5.1094, 3.5824],
        [3.7434, 5.7431, 3.3892],
        [4.2794, 4.9769, 5.5314]])

In [81]:
#4
a = torch.rand(3,3)
a.normal_

<function Tensor.normal_>

In [87]:
#5
a= torch.Tensor([1,1,1,0,1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [88]:
#6
a = torch.rand(3,1)
a.expand(3,4) #extend(): 크기가 1인 차원을 지정한 크기로 늘림

tensor([[0.4424, 0.4424, 0.4424, 0.4424],
        [0.5406, 0.5406, 0.5406, 0.5406],
        [0.6725, 0.6725, 0.6725, 0.6725]])

In [89]:
#7
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a,b) #배치 행렬 곱셈: 첫번째 차원을 배치 차원으로 인식

tensor([[[2.0173, 1.8379, 1.7570, 1.4625],
         [1.6128, 1.0536, 0.8923, 1.1944],
         [2.0652, 1.5962, 1.6332, 1.6294],
         [1.7789, 1.4160, 1.1003, 1.3703]],

        [[0.8152, 2.3730, 1.3911, 1.1896],
         [1.2025, 1.9932, 1.4912, 1.3987],
         [0.8897, 1.5277, 0.9361, 0.5876],
         [0.5381, 1.4137, 0.7752, 0.5163]],

        [[0.9799, 1.2481, 1.7319, 1.8113],
         [1.3510, 1.1865, 1.5942, 1.7817],
         [0.7258, 1.1453, 1.5153, 1.4434],
         [0.8544, 1.3446, 1.8362, 1.7614]]])

In [90]:
#8
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a,b.unsqueeze(0).expand(a.size(0),*b.size()))

tensor([[[0.8551, 0.6825, 0.6279, 0.5291],
         [1.0774, 0.9862, 0.9710, 0.7477],
         [0.9849, 1.0841, 0.7878, 0.8098],
         [1.5191, 1.2466, 1.2565, 1.1384]],

        [[0.7059, 0.8819, 0.8808, 0.7877],
         [1.1928, 1.2686, 1.1062, 0.8081],
         [1.3679, 1.3462, 1.1821, 0.8181],
         [0.5553, 0.5320, 0.2881, 0.4666]],

        [[1.0483, 0.9656, 0.9135, 0.6853],
         [1.2374, 1.3297, 1.1526, 0.5813],
         [1.2865, 1.1604, 1.0221, 0.7346],
         [0.8079, 0.8123, 0.5712, 0.6136]]])